function [pc, dm] = createPointCloud(left, right, stereo_parameters)
  [left, right, mask] = preprocessImages(left, right, stereo_parameters);
  dm = disparity(left, right, ...
    'BlockSize', 15, ...
    'DisparityRange', [-128, 128], ...
    'Method', 'SemiGlobal',...
    'UniquenessThreshold', 0,...
    'DistanceThreshold', 15,...
    'ContrastThreshold', 0.7);
  % remove unreliable pixels
  unreliable = (dm < -1e12) | (1 - mask);
  dm = dm .* (1 - unreliable);
  %imshow(dm, [0, 256]);
  %colormap(gca, jet);
  %colorbar
  pc = reconstructScene(dm, stereo_parameters);
end
