function pc = createPointCloud(left, right, stereo_parameters)
  [left_rect, right_rect] = rectifyStereoImages(left, right, stereo_parameters,...
                                                'OutputView', 'full');
  dm = disparity(left_rect, right_rect, ...
    'BlockSize', 15, ...
    'DisparityRange', [32, 1024], ...
    'Method', 'SemiGlobal',...
    'UniquenessThreshold', 10);
  pc = reconstructScene(dm, stereo_parameters);
end
